version: "3"
services:
    puppeteer:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - .:/app
        command: npm start
